theme: jekyll-theme-cayman
title: SMI 2021
plugins:
  - jekyll-optional-front-matter
baseurl: /TestSMISite

collections:
  session:
      output: true
      permalink: /invited/:name
      sort_by: order